# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "~> 1.2.6"
  backend "s3" {
    bucket         = "devops-workshop-dadd30a3-7b5e-4c7e-baca-9804ce726d09"
    key            = "devops-us-east-1.k8s.local/terragrunt/terraform.tfstate"
    region         = "us-east-1"
  }
}
